<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCurrencyTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('currency', function (Blueprint $table) {
            $table->increments('id');
            $table->string('code');
            $table->timestamps();
        });

        DB::table('currency')->insert(array(
            array('code' => 'AED'),
            array('code' => 'AFN'),
            array('code' => 'ALL'),
            array('code' => 'AMD'),
            array('code' => 'ANG'),
            array('code' => 'AOA'),
            array('code' => 'ARS'),
            array('code' => 'AUD'),
            array('code' => 'AWG'),
            array('code' => 'AZN'),
            array('code' => 'BAM'),
            array('code' => 'BBD'),
            array('code' => 'BDT'),
            array('code' => 'BGN'),
            array('code' => 'BHD'),
            array('code' => 'BIF'),
            array('code' => 'BMD'),
            array('code' => 'BND'),
            array('code' => 'BOB'),
            array('code' => 'BOV'),
            array('code' => 'BRL'),
            array('code' => 'BSD'),
            array('code' => 'BTN'),
            array('code' => 'BWP'),
            array('code' => 'BYN'),
            array('code' => 'BZD'),
            array('code' => 'CAD'),
            array('code' => 'CDF'),
            array('code' => 'CHE'),
            array('code' => 'CHF'),
            array('code' => 'CHW'),
            array('code' => 'CLF'),
            array('code' => 'CLP'),
            array('code' => 'CNY'),
            array('code' => 'COP'),
            array('code' => 'COU'),
            array('code' => 'CRC'),
            array('code' => 'CUC'),
            array('code' => 'CUP'),
            array('code' => 'CVE'),
            array('code' => 'CZK'),
            array('code' => 'DJF'),
            array('code' => 'DKK'),
            array('code' => 'DOP'),
            array('code' => 'DZD'),
            array('code' => 'EGP'),
            array('code' => 'ERN'),
            array('code' => 'ETB'),
            array('code' => 'EUR'),
            array('code' => 'FJD'),
            array('code' => 'FKP'),
            array('code' => 'GBP'),
            array('code' => 'GEL'),
            array('code' => 'GHS'),
            array('code' => 'GIP'),
            array('code' => 'GMD'),
            array('code' => 'GNF'),
            array('code' => 'GTQ'),
            array('code' => 'GYD'),
            array('code' => 'HKD'),
            array('code' => 'HNL'),
            array('code' => 'HRK'),
            array('code' => 'HTG'),
            array('code' => 'HUF'),
            array('code' => 'IDR'),
            array('code' => 'ILS'),
            array('code' => 'INR'),
            array('code' => 'IQD'),
            array('code' => 'IRR'),
            array('code' => 'ISK'),
            array('code' => 'JMD'),
            array('code' => 'JOD'),
            array('code' => 'JPY'),
            array('code' => 'KES'),
            array('code' => 'KGS'),
            array('code' => 'KHR'),
            array('code' => 'KMF'),
            array('code' => 'KPW'),
            array('code' => 'KRW'),
            array('code' => 'KWD'),
            array('code' => 'KYD'),
            array('code' => 'KZT'),
            array('code' => 'LAK'),
            array('code' => 'LBP'),
            array('code' => 'LKR'),
            array('code' => 'LRD'),
            array('code' => 'LSL'),
            array('code' => 'LYD'),
            array('code' => 'MAD'),
            array('code' => 'MDL'),
            array('code' => 'MGA'),
            array('code' => 'MKD'),
            array('code' => 'MMK'),
            array('code' => 'MNT'),
            array('code' => 'MOP'),
            array('code' => 'MRO'),
            array('code' => 'MUR'),
            array('code' => 'MVR'),
            array('code' => 'MWK'),
            array('code' => 'MXN'),
            array('code' => 'MXV'),
            array('code' => 'MYR'),
            array('code' => 'MZN'),
            array('code' => 'NAD'),
            array('code' => 'NGN'),
            array('code' => 'NIO'),
            array('code' => 'NOK'),
            array('code' => 'NPR'),
            array('code' => 'NZD'),
            array('code' => 'OMR'),
            array('code' => 'PAB'),
            array('code' => 'PEN'),
            array('code' => 'PGK'),
            array('code' => 'PHP'),
            array('code' => 'PKR'),
            array('code' => 'PLN'),
            array('code' => 'PYG'),
            array('code' => 'QAR'),
            array('code' => 'RON'),
            array('code' => 'RSD'),
            array('code' => 'RUB'),
            array('code' => 'RWF'),
            array('code' => 'SAR'),
            array('code' => 'SBD'),
            array('code' => 'SCR'),
            array('code' => 'SDG'),
            array('code' => 'SEK'),
            array('code' => 'SGD'),
            array('code' => 'SHP'),
            array('code' => 'SLL'),
            array('code' => 'SOS'),
            array('code' => 'SRD'),
            array('code' => 'SSP'),
            array('code' => 'STD'),
            array('code' => 'SVC'),
            array('code' => 'SYP'),
            array('code' => 'SZL'),
            array('code' => 'THB'),
            array('code' => 'TJS'),
            array('code' => 'TMT'),
            array('code' => 'TND'),
            array('code' => 'TOP'),
            array('code' => 'TRY'),
            array('code' => 'TTD'),
            array('code' => 'TWD'),
            array('code' => 'TZS'),
            array('code' => 'UAH'),
            array('code' => 'UGX'),
            array('code' => 'USD'),
            array('code' => 'USN'),
            array('code' => 'UYI'),
            array('code' => 'UYU'),
            array('code' => 'UZS'),
            array('code' => 'VEF'),
            array('code' => 'VND'),
            array('code' => 'VUV'),
            array('code' => 'WST'),
            array('code' => 'XAF'),
            array('code' => 'XAG'),
            array('code' => 'XAU'),
            array('code' => 'XBA'),
            array('code' => 'XBB'),
            array('code' => 'XBC'),
            array('code' => 'XBD'),
            array('code' => 'XCD'),
            array('code' => 'XDR'),
            array('code' => 'XOF'),
            array('code' => 'XPD'),
            array('code' => 'XPF'),
            array('code' => 'XPT'),
            array('code' => 'XSU'),
            array('code' => 'XTS'),
            array('code' => 'XUA'),
            array('code' => 'XXX'),
            array('code' => 'YER'),
            array('code' => 'ZAR'),
            array('code' => 'ZMW'),
            array('code' => 'ZWL'),
        ));
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('currency');
    }
}
